version: '3'
services:
  fastapi:
    build: .
    volumes:
      - .:/app  
    ports:
      - "8001:8001"
    command: 
      - "uvicorn"
      - "app:app"
      - "--reload"
      - "--port=8001"
      - "--host=0.0.0.0"
